  version: "3.7"    
  services:
    mucgpt:
      image: mucgpt:latest
      container_name: MUCGPT
      ports:
        - "8000:8000"
      volumes:
        - "./config/local.json:/code/config.json"
        - "./config/base.json:/code/base.json"
      environment:
          https_proxy: "http://internet-proxy-client.muenchen.de:80" 
          http_proxy: "http://internet-proxy-client.muenchen.de:80" 