export const enum STORAGE_KEYS {
    TERMS_OF_USE_READ = "TERMS_OF_USE_READ",
    SETTINGS_LANGUAGE = "SETTINGS_LANGUAGE",
    SETTINGS_LLM = "SETTINGS_LLM",
    SETTINGS_FONT_SCALING = "SETTINGS_FONT_SCALING",
    SETTINGS_IS_LIGHT_THEME = "SETTINGS_IS_LIGHT_THEME",
    VERSION_UPDATE_SEEN = "VERSION_UPDATE_SEEN",
    HOME_ASSISTANT_MODE = "HOME_ASSISTANT_MODE",
    CHAT_FILE_IDS = "chatFileIds",
    SELECTED_TOOLS = "SELECTED_TOOLS",
    SETTINGS_TRANSCRIPTION_ENABLED = "SETTINGS_TRANSCRIPTION_ENABLED",
    SETTINGS_TRANSCRIPTION_MODEL_ID = "SETTINGS_TRANSCRIPTION_MODEL_ID",
    SETTINGS_TRANSCRIPTION_DOWNLOADED_MODELS = "SETTINGS_TRANSCRIPTION_DOWNLOADED_MODELS"
}
