import { Theme, makeStyles } from "@fluentui/react-components";
import { tokens } from "@fluentui/react-theme";

export const useStyles = makeStyles({
    header: {
        backgroundColor: tokens.colorBrandBackground2,
        color: tokens.colorBrandForeground2
    }
});

export const enum STORAGE_KEYS {
    TERMS_OF_USE_READ = "TERMS_OF_USE_READ",
    SETTINGS_LANGUAGE = "SETTINGS_LANGUAGE",
    SETTINGS_LLM = "SETTINGS_LLM",
    SETTINGS_FONT_SCALING = "SETTINGS_FONT_SCALING",
    SETTINGS_IS_LIGHT_THEME = "SETTINGS_IS_LIGHT_THEME",
    VERSION_UPDATE_SEEN = "VERSION_UPDATE_SEEN",
    SHOW_SIDEBAR = "SHOW_SIDEBAR"
}

type MUCGPTTheme = Theme & {
    primary: string;
    on_primary: string;
    outline: string;
    primary_container: string;
    on_primary_container: string;
    surface: string;
    on_surface: string;
    on_surface_variant: string;
    disabled: string;
};

export const adjustTheme = (isLight: boolean) => {
    const mucgpt_dark_tokens = {
        primary: "#94B9AF",
        on_primary: "#003631",
        outline: "#BEC9C6",
        primary_container: "#E6EFED",
        on_primary_container: "#5C6664",
        surface: "#F7FAF8",
        on_surface: "#191C1B",
        on_surface_variant: "#3A413E",
        disabled: "A9A3A3"
    };

    //TODO change this
    const mucgpt_light_tokens = {
        primary: "#006D5B",
        on_primary: "#FFFFFF",
        outline: "#3F8E86",
        primary_container: "#7BBBB4",
        on_primary_container: "#FFFFFF",
        surface: "#323130",
        on_surface: "#F7FAF9",
        on_surface_variant: "#C8C8C8",
        disabled: "666161"
    };

    const variant = isLight ? mucgpt_light_tokens : mucgpt_dark_tokens;

    const theme: MUCGPTTheme = {
        ...variant,
        borderRadiusNone: "0",
        borderRadiusSmall: "4px",
        borderRadiusMedium: "6px",
        borderRadiusLarge: "8px",
        borderRadiusXLarge: "12px",
        borderRadiusCircular: "10000px",
        fontSizeBase100: "10px",
        fontSizeBase200: "12px",
        fontSizeBase300: "14px",
        fontSizeBase400: "16px",
        fontSizeBase500: "20px",
        fontSizeBase600: "24px",
        fontSizeHero700: "28px",
        fontSizeHero800: "32px",
        fontSizeHero900: "40px",
        fontSizeHero1000: "68px",
        lineHeightBase100: "14px",
        lineHeightBase200: "16px",
        lineHeightBase300: "20px",
        lineHeightBase400: "22px",
        lineHeightBase500: "28px",
        lineHeightBase600: "32px",
        lineHeightHero700: "36px",
        lineHeightHero800: "40px",
        lineHeightHero900: "52px",
        lineHeightHero1000: "92px",
        fontFamilyBase: "'Segoe UI', 'Segoe UI Web (West European)', -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif",
        fontFamilyMonospace: "Consolas, 'Courier New', Courier, monospace",
        fontFamilyNumeric: "Bahnschrift, 'Segoe UI', 'Segoe UI Web (West European)', -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif",
        fontWeightRegular: 400,
        fontWeightMedium: 500,
        fontWeightSemibold: 600,
        fontWeightBold: 700,
        strokeWidthThin: "1px",
        strokeWidthThick: "2px",
        strokeWidthThicker: "3px",
        strokeWidthThickest: "4px",
        spacingHorizontalNone: "0",
        spacingHorizontalXXS: "2px",
        spacingHorizontalXS: "4px",
        spacingHorizontalSNudge: "6px",
        spacingHorizontalS: "8px",
        spacingHorizontalMNudge: "10px",
        spacingHorizontalM: "12px",
        spacingHorizontalL: "16px",
        spacingHorizontalXL: "20px",
        spacingHorizontalXXL: "24px",
        spacingHorizontalXXXL: "32px",
        spacingVerticalNone: "0",
        spacingVerticalXXS: "2px",
        spacingVerticalXS: "4px",
        spacingVerticalSNudge: "6px",
        spacingVerticalS: "8px",
        spacingVerticalMNudge: "10px",
        spacingVerticalM: "12px",
        spacingVerticalL: "16px",
        spacingVerticalXL: "20px",
        spacingVerticalXXL: "24px",
        spacingVerticalXXXL: "32px",
        durationUltraFast: "50ms",
        durationFaster: "100ms",
        durationFast: "150ms",
        durationNormal: "200ms",
        durationGentle: "250ms",
        durationSlow: "300ms",
        durationSlower: "400ms",
        durationUltraSlow: "500ms",
        curveAccelerateMax: "cubic-bezier(0.9,0.1,1,0.2)",
        curveAccelerateMid: "cubic-bezier(1,0,1,1)",
        curveAccelerateMin: "cubic-bezier(0.8,0,0.78,1)",
        curveDecelerateMax: "cubic-bezier(0.1,0.9,0.2,1)",
        curveDecelerateMid: "cubic-bezier(0,0,0,1)",
        curveDecelerateMin: "cubic-bezier(0.33,0,0.1,1)",
        curveEasyEaseMax: "cubic-bezier(0.8,0,0.2,1)",
        curveEasyEase: "cubic-bezier(0.33,0,0.67,1)",
        curveLinear: "cubic-bezier(0,0,1,1)",
        colorNeutralForeground1: "#323130",
        colorNeutralForeground1Hover: "#323130",
        colorNeutralForeground1Pressed: "#323130",
        colorNeutralForeground1Selected: "#323130",
        colorNeutralForeground2: "#605e5c",
        colorNeutralForeground2Hover: "#323130",
        colorNeutralForeground2Pressed: "#323130",
        colorNeutralForeground2Selected: "#323130",
        colorNeutralForeground2BrandHover: "#003631",
        colorNeutralForeground2BrandPressed: "#287870",
        colorNeutralForeground2BrandSelected: "#003631",
        colorNeutralForeground3: "#a19f9d",
        colorNeutralForeground3Hover: "#605e5c",
        colorNeutralForeground3Pressed: "#605e5c",
        colorNeutralForeground3Selected: "#605e5c",
        colorNeutralForeground3BrandHover: "#003631",
        colorNeutralForeground3BrandPressed: "#287870",
        colorNeutralForeground3BrandSelected: "#003631",
        colorNeutralForeground4: "#cacccb",
        colorNeutralForegroundDisabled: "#c2c4c3",
        colorNeutralForegroundInvertedDisabled: "rgba(255, 255, 255, 0.4)",
        colorBrandForegroundLink: "#287870",
        colorBrandForegroundLinkHover: "#16625a",
        colorBrandForegroundLinkPressed: "#084c45",
        colorBrandForegroundLinkSelected: "#287870",
        colorNeutralForeground2Link: "#605e5c",
        colorNeutralForeground2LinkHover: "#323130",
        colorNeutralForeground2LinkPressed: "#323130",
        colorNeutralForeground2LinkSelected: "#323130",
        colorCompoundBrandForeground1: "#003631",
        colorCompoundBrandForeground1Hover: "#287870",
        colorCompoundBrandForeground1Pressed: "#16625a",
        colorBrandForeground1: "#003631",
        colorBrandForeground2: "#287870",
        colorBrandForeground2Hover: "#287870",
        colorBrandForeground2Pressed: "#287870",
        colorNeutralForeground1Static: "#323130",
        colorNeutralForegroundStaticInverted: "#F7FAF9",
        colorNeutralForegroundInverted: "#F7FAF9",
        colorNeutralForegroundInvertedHover: "#F7FAF9",
        colorNeutralForegroundInvertedPressed: "#F7FAF9",
        colorNeutralForegroundInvertedSelected: "#F7FAF9",
        colorNeutralForegroundInverted2: "#F7FAF9",
        colorNeutralForegroundOnBrand: "#F7FAF9",
        colorNeutralForegroundInvertedLink: "#F7FAF9",
        colorNeutralForegroundInvertedLinkHover: "#F7FAF9",
        colorNeutralForegroundInvertedLinkPressed: "#F7FAF9",
        colorNeutralForegroundInvertedLinkSelected: "#F7FAF9",
        colorBrandForegroundInverted: "#3f8e86",
        colorBrandForegroundInvertedHover: "#5aa49d",
        colorBrandForegroundInvertedPressed: "#3f8e86",
        colorBrandForegroundOnLight: "#003631",
        colorBrandForegroundOnLightHover: "#287870",
        colorBrandForegroundOnLightPressed: "#16625a",
        colorBrandForegroundOnLightSelected: "#16625a",
        colorNeutralBackground1: "#F7FAF9",
        colorNeutralBackground1Hover: "#edefee",
        colorNeutralBackground1Pressed: "#d4d6d5",
        colorNeutralBackground1Selected: "#e3e5e5",
        colorNeutralBackground2: "#f1f3f2",
        colorNeutralBackground2Hover: "#edefee",
        colorNeutralBackground2Pressed: "#d4d6d5",
        colorNeutralBackground2Selected: "#e3e5e5",
        colorNeutralBackground3: "#edefee",
        colorNeutralBackground3Hover: "#e3e5e5",
        colorNeutralBackground3Pressed: "#cacccb",
        colorNeutralBackground3Selected: "#d4d6d5",
        colorNeutralBackground4: "#edefee",
        colorNeutralBackground4Hover: "#f1f3f2",
        colorNeutralBackground4Pressed: "#edefee",
        colorNeutralBackground4Selected: "#F7FAF9",
        colorNeutralBackground5: "#e3e5e5",
        colorNeutralBackground5Hover: "#edefee",
        colorNeutralBackground5Pressed: "#edefee",
        colorNeutralBackground5Selected: "#f1f3f2",
        colorNeutralBackground6: "#e3e5e5",
        colorNeutralBackgroundInverted: "#605e5c",
        colorNeutralBackgroundStatic: "#333333",
        colorNeutralBackgroundAlpha: "rgba(255, 255, 255, 0.5)",
        colorNeutralBackgroundAlpha2: "rgba(255, 255, 255, 0.8)",
        colorSubtleBackground: "transparent",
        colorSubtleBackgroundHover: "#edefee",
        colorSubtleBackgroundPressed: "#d4d6d5",
        colorSubtleBackgroundSelected: "#e3e5e5",
        colorSubtleBackgroundLightAlphaHover: "rgba(255, 255, 255, 0.8)",
        colorSubtleBackgroundLightAlphaPressed: "rgba(255, 255, 255, 0.5)",
        colorSubtleBackgroundLightAlphaSelected: "transparent",
        colorSubtleBackgroundInverted: "transparent",
        colorSubtleBackgroundInvertedHover: "rgba(0, 0, 0, 0.1)",
        colorSubtleBackgroundInvertedPressed: "rgba(0, 0, 0, 0.3)",
        colorSubtleBackgroundInvertedSelected: "rgba(0, 0, 0, 0.2)",
        colorTransparentBackground: "transparent",
        colorTransparentBackgroundHover: "transparent",
        colorTransparentBackgroundPressed: "transparent",
        colorTransparentBackgroundSelected: "transparent",
        colorNeutralBackgroundDisabled: "#edefee",
        colorNeutralBackgroundInvertedDisabled: "rgba(255, 255, 255, 0.1)",
        colorNeutralStencil1: "#e3e5e5",
        colorNeutralStencil2: "#f1f3f2",
        colorNeutralStencil1Alpha: "rgba(0, 0, 0, 0.1)",
        colorNeutralStencil2Alpha: "rgba(0, 0, 0, 0.05)",
        colorBackgroundOverlay: "rgba(0, 0, 0, 0.4)",
        colorScrollbarOverlay: "rgba(0, 0, 0, 0.5)",
        colorBrandBackground: "#003631",
        colorBrandBackgroundHover: "#287870",
        colorBrandBackgroundPressed: "#084c45",
        colorBrandBackgroundSelected: "#16625a",
        colorCompoundBrandBackground: "#003631",
        colorCompoundBrandBackgroundHover: "#287870",
        colorCompoundBrandBackgroundPressed: "#16625a",
        colorBrandBackgroundStatic: "#003631",
        colorBrandBackground2: "#cbe7e4",
        colorBrandBackground2Hover: "#cbe7e4",
        colorBrandBackground2Pressed: "#cbe7e4",
        colorBrandBackground3Static: "#16625a",
        colorBrandBackground4Static: "#084c45",
        colorBrandBackgroundInverted: "#F7FAF9",
        colorBrandBackgroundInvertedHover: "#cbe7e4",
        colorBrandBackgroundInvertedPressed: "#7bbbb4",
        colorBrandBackgroundInvertedSelected: "#a1d1cc",
        colorNeutralCardBackground: "#fafafa",
        colorNeutralCardBackgroundHover: "#F7FAF9",
        colorNeutralCardBackgroundPressed: "#f5f5f5",
        colorNeutralCardBackgroundSelected: "#ebebeb",
        colorNeutralCardBackgroundDisabled: "#f0f0f0",
        colorNeutralStrokeAccessible: "#605e5c",
        colorNeutralStrokeAccessibleHover: "#605e5c",
        colorNeutralStrokeAccessiblePressed: "#605e5c",
        colorNeutralStrokeAccessibleSelected: "#003631",
        colorNeutralStroke1: "#cacccb",
        colorNeutralStroke1Hover: "#c2c4c3",
        colorNeutralStroke1Pressed: "#c2c4c3",
        colorNeutralStroke1Selected: "#c2c4c3",
        colorNeutralStroke2: "#d4d6d5",
        colorNeutralStroke3: "#edefee",
        colorNeutralStrokeSubtle: "#d4d6d5",
        colorNeutralStrokeOnBrand: "#F7FAF9",
        colorNeutralStrokeOnBrand2: "#F7FAF9",
        colorNeutralStrokeOnBrand2Hover: "#F7FAF9",
        colorNeutralStrokeOnBrand2Pressed: "#F7FAF9",
        colorNeutralStrokeOnBrand2Selected: "#F7FAF9",
        colorBrandStroke1: "#003631",
        colorBrandStroke2: "#7bbbb4",
        colorBrandStroke2Hover: "#7bbbb4",
        colorBrandStroke2Pressed: "#7bbbb4",
        colorBrandStroke2Contrast: "#7bbbb4",
        colorCompoundBrandStroke: "#003631",
        colorCompoundBrandStrokeHover: "#287870",
        colorCompoundBrandStrokePressed: "#16625a",
        colorNeutralStrokeDisabled: "#d4d6d5",
        colorNeutralStrokeInvertedDisabled: "rgba(255, 255, 255, 0.4)",
        colorTransparentStroke: "transparent",
        colorTransparentStrokeInteractive: "transparent",
        colorTransparentStrokeDisabled: "transparent",
        colorNeutralStrokeAlpha: "rgba(0, 0, 0, 0.05)",
        colorNeutralStrokeAlpha2: "rgba(255, 255, 255, 0.2)",
        colorStrokeFocus1: "#F7FAF9",
        colorStrokeFocus2: "#000000",
        colorNeutralShadowAmbient: "rgba(0,0,0,0.12)",
        colorNeutralShadowKey: "rgba(0,0,0,0.14)",
        colorNeutralShadowAmbientLighter: "rgba(0,0,0,0.06)",
        colorNeutralShadowKeyLighter: "rgba(0,0,0,0.07)",
        colorNeutralShadowAmbientDarker: "rgba(0,0,0,0.20)",
        colorNeutralShadowKeyDarker: "rgba(0,0,0,0.24)",
        colorBrandShadowAmbient: "rgba(0,0,0,0.30)",
        colorBrandShadowKey: "rgba(0,0,0,0.25)",
        colorPaletteRedBackground1: "#fdf6f6",
        colorPaletteRedBackground2: "#f1bbbc",
        colorPaletteRedBackground3: "#d13438",
        colorPaletteRedForeground1: "#bc2f32",
        colorPaletteRedForeground2: "#751d1f",
        colorPaletteRedForeground3: "#d13438",
        colorPaletteRedBorderActive: "#d13438",
        colorPaletteRedBorder1: "#f1bbbc",
        colorPaletteRedBorder2: "#d13438",
        colorPaletteGreenBackground1: "#f1faf1",
        colorPaletteGreenBackground2: "#9fd89f",
        colorPaletteGreenBackground3: "#107c10",
        colorPaletteGreenForeground1: "#0e700e",
        colorPaletteGreenForeground2: "#094509",
        colorPaletteGreenForeground3: "#107c10",
        colorPaletteGreenBorderActive: "#107c10",
        colorPaletteGreenBorder1: "#9fd89f",
        colorPaletteGreenBorder2: "#107c10",
        colorPaletteDarkOrangeBackground1: "#fdf6f3",
        colorPaletteDarkOrangeBackground2: "#f4bfab",
        colorPaletteDarkOrangeBackground3: "#da3b01",
        colorPaletteDarkOrangeForeground1: "#c43501",
        colorPaletteDarkOrangeForeground2: "#7a2101",
        colorPaletteDarkOrangeForeground3: "#da3b01",
        colorPaletteDarkOrangeBorderActive: "#da3b01",
        colorPaletteDarkOrangeBorder1: "#f4bfab",
        colorPaletteDarkOrangeBorder2: "#da3b01",
        colorPaletteYellowBackground1: "#fffef5",
        colorPaletteYellowBackground2: "#fef7b2",
        colorPaletteYellowBackground3: "#fde300",
        colorPaletteYellowForeground1: "#817400",
        colorPaletteYellowForeground2: "#817400",
        colorPaletteYellowForeground3: "#fde300",
        colorPaletteYellowBorderActive: "#fde300",
        colorPaletteYellowBorder1: "#fef7b2",
        colorPaletteYellowBorder2: "#fde300",
        colorPaletteBerryBackground1: "#fdf5fc",
        colorPaletteBerryBackground2: "#edbbe7",
        colorPaletteBerryBackground3: "#c239b3",
        colorPaletteBerryForeground1: "#af33a1",
        colorPaletteBerryForeground2: "#6d2064",
        colorPaletteBerryForeground3: "#c239b3",
        colorPaletteBerryBorderActive: "#c239b3",
        colorPaletteBerryBorder1: "#edbbe7",
        colorPaletteBerryBorder2: "#c239b3",
        colorPaletteLightGreenBackground1: "#f2fbf2",
        colorPaletteLightGreenBackground2: "#a7e3a5",
        colorPaletteLightGreenBackground3: "#13a10e",
        colorPaletteLightGreenForeground1: "#11910d",
        colorPaletteLightGreenForeground2: "#0b5a08",
        colorPaletteLightGreenForeground3: "#13a10e",
        colorPaletteLightGreenBorderActive: "#13a10e",
        colorPaletteLightGreenBorder1: "#a7e3a5",
        colorPaletteLightGreenBorder2: "#13a10e",
        colorPaletteMarigoldBackground1: "#fefbf4",
        colorPaletteMarigoldBackground2: "#f9e2ae",
        colorPaletteMarigoldBackground3: "#eaa300",
        colorPaletteMarigoldForeground1: "#d39300",
        colorPaletteMarigoldForeground2: "#835b00",
        colorPaletteMarigoldForeground3: "#eaa300",
        colorPaletteMarigoldBorderActive: "#eaa300",
        colorPaletteMarigoldBorder1: "#f9e2ae",
        colorPaletteMarigoldBorder2: "#eaa300",
        colorPaletteRedForegroundInverted: "#dc5e62",
        colorPaletteGreenForegroundInverted: "#359b35",
        colorPaletteYellowForegroundInverted: "#fef7b2",
        colorPaletteDarkRedBackground2: "#d69ca5",
        colorPaletteDarkRedForeground2: "#420610",
        colorPaletteDarkRedBorderActive: "#750b1c",
        colorPaletteCranberryBackground2: "#eeacb2",
        colorPaletteCranberryForeground2: "#6e0811",
        colorPaletteCranberryBorderActive: "#c50f1f",
        colorPalettePumpkinBackground2: "#efc4ad",
        colorPalettePumpkinForeground2: "#712d09",
        colorPalettePumpkinBorderActive: "#ca5010",
        colorPalettePeachBackground2: "#ffddb3",
        colorPalettePeachForeground2: "#8f4e00",
        colorPalettePeachBorderActive: "#ff8c00",
        colorPaletteGoldBackground2: "#ecdfa5",
        colorPaletteGoldForeground2: "#6c5700",
        colorPaletteGoldBorderActive: "#c19c00",
        colorPaletteBrassBackground2: "#e0cea2",
        colorPaletteBrassForeground2: "#553e06",
        colorPaletteBrassBorderActive: "#986f0b",
        colorPaletteBrownBackground2: "#ddc3b0",
        colorPaletteBrownForeground2: "#50301a",
        colorPaletteBrownBorderActive: "#8e562e",
        colorPaletteForestBackground2: "#bdd99b",
        colorPaletteForestForeground2: "#294903",
        colorPaletteForestBorderActive: "#498205",
        colorPaletteSeafoamBackground2: "#a8f0cd",
        colorPaletteSeafoamForeground2: "#00723b",
        colorPaletteSeafoamBorderActive: "#00cc6a",
        colorPaletteDarkGreenBackground2: "#9ad29a",
        colorPaletteDarkGreenForeground2: "#063b06",
        colorPaletteDarkGreenBorderActive: "#0b6a0b",
        colorPaletteLightTealBackground2: "#a6e9ed",
        colorPaletteLightTealForeground2: "#00666d",
        colorPaletteLightTealBorderActive: "#00b7c3",
        colorPaletteTealBackground2: "#9bd9db",
        colorPaletteTealForeground2: "#02494c",
        colorPaletteTealBorderActive: "#038387",
        colorPaletteSteelBackground2: "#94c8d4",
        colorPaletteSteelForeground2: "#00333f",
        colorPaletteSteelBorderActive: "#005b70",
        colorPaletteBlueBackground2: "#a9d3f2",
        colorPaletteBlueForeground2: "#004377",
        colorPaletteBlueBorderActive: "#0078d4",
        colorPaletteRoyalBlueBackground2: "#9abfdc",
        colorPaletteRoyalBlueForeground2: "#002c4e",
        colorPaletteRoyalBlueBorderActive: "#004e8c",
        colorPaletteCornflowerBackground2: "#c8d1fa",
        colorPaletteCornflowerForeground2: "#2c3c85",
        colorPaletteCornflowerBorderActive: "#4f6bed",
        colorPaletteNavyBackground2: "#a3b2e8",
        colorPaletteNavyForeground2: "#001665",
        colorPaletteNavyBorderActive: "#0027b4",
        colorPaletteLavenderBackground2: "#d2ccf8",
        colorPaletteLavenderForeground2: "#3f3682",
        colorPaletteLavenderBorderActive: "#7160e8",
        colorPalettePurpleBackground2: "#c6b1de",
        colorPalettePurpleForeground2: "#341a51",
        colorPalettePurpleBorderActive: "#5c2e91",
        colorPaletteGrapeBackground2: "#d9a7e0",
        colorPaletteGrapeForeground2: "#4c0d55",
        colorPaletteGrapeBorderActive: "#881798",
        colorPaletteLilacBackground2: "#e6bfed",
        colorPaletteLilacForeground2: "#63276d",
        colorPaletteLilacBorderActive: "#b146c2",
        colorPalettePinkBackground2: "#f7c0e3",
        colorPalettePinkForeground2: "#80215d",
        colorPalettePinkBorderActive: "#e43ba6",
        colorPaletteMagentaBackground2: "#eca5d1",
        colorPaletteMagentaForeground2: "#6b0043",
        colorPaletteMagentaBorderActive: "#bf0077",
        colorPalettePlumBackground2: "#d696c0",
        colorPalettePlumForeground2: "#43002b",
        colorPalettePlumBorderActive: "#77004d",
        colorPaletteBeigeBackground2: "#d7d4d4",
        colorPaletteBeigeForeground2: "#444241",
        colorPaletteBeigeBorderActive: "#7a7574",
        colorPaletteMinkBackground2: "#cecccb",
        colorPaletteMinkForeground2: "#343231",
        colorPaletteMinkBorderActive: "#5d5a58",
        colorPalettePlatinumBackground2: "#cdd6d8",
        colorPalettePlatinumForeground2: "#3b4447",
        colorPalettePlatinumBorderActive: "#69797e",
        colorPaletteAnchorBackground2: "#bcc3c7",
        colorPaletteAnchorForeground2: "#202427",
        colorPaletteAnchorBorderActive: "#394146",
        colorStatusSuccessBackground1: "#f1faf1",
        colorStatusSuccessBackground2: "#9fd89f",
        colorStatusSuccessBackground3: "#107c10",
        colorStatusSuccessForeground1: "#0e700e",
        colorStatusSuccessForeground2: "#094509",
        colorStatusSuccessForeground3: "#107c10",
        colorStatusSuccessForegroundInverted: "#54b054",
        colorStatusSuccessBorderActive: "#107c10",
        colorStatusSuccessBorder1: "#9fd89f",
        colorStatusSuccessBorder2: "#107c10",
        colorStatusWarningBackground1: "#fff9f5",
        colorStatusWarningBackground2: "#fdcfb4",
        colorStatusWarningBackground3: "#f7630c",
        colorStatusWarningForeground1: "#bc4b09",
        colorStatusWarningForeground2: "#8a3707",
        colorStatusWarningForeground3: "#bc4b09",
        colorStatusWarningForegroundInverted: "#faa06b",
        colorStatusWarningBorderActive: "#f7630c",
        colorStatusWarningBorder1: "#fdcfb4",
        colorStatusWarningBorder2: "#bc4b09",
        colorStatusDangerBackground1: "#fdf3f4",
        colorStatusDangerBackground2: "#eeacb2",
        colorStatusDangerBackground3: "#c50f1f",
        colorStatusDangerForeground1: "#b10e1c",
        colorStatusDangerForeground2: "#6e0811",
        colorStatusDangerForeground3: "#c50f1f",
        colorStatusDangerForegroundInverted: "#dc626d",
        colorStatusDangerBorderActive: "#c50f1f",
        colorStatusDangerBorder1: "#eeacb2",
        colorStatusDangerBorder2: "#c50f1f",
        colorStatusDangerBackground3Hover: "#b10e1c",
        colorStatusDangerBackground3Pressed: "#960b18",
        shadow2: "0 0 2px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.14)",
        shadow4: "0 1.6px 3.6px 0 rgba(0, 0, 0, 0.132), 0 0.3px 0.9px 0 rgba(0, 0, 0, 0.108)",
        shadow8: "0 3.2px 7.2px 0 rgba(0, 0, 0, 0.132), 0 0.6px 1.8px 0 rgba(0, 0, 0, 0.108)",
        shadow16: "0 6.4px 14.4px 0 rgba(0, 0, 0, 0.132), 0 1.2px 3.6px 0 rgba(0, 0, 0, 0.108)",
        shadow28: "0 0 8px rgba(0,0,0,0.12), 0 14px 28px rgba(0,0,0,0.14)",
        shadow64: "0 25.6px 57.6px 0 rgba(0, 0, 0, 0.22), 0 4.8px 14.4px 0 rgba(0, 0, 0, 0.18)",
        shadow2Brand: "0 0 2px rgba(0,0,0,0.30), 0 1px 2px rgba(0,0,0,0.25)",
        shadow4Brand: "0 0 2px rgba(0,0,0,0.30), 0 2px 4px rgba(0,0,0,0.25)",
        shadow8Brand: "0 0 2px rgba(0,0,0,0.30), 0 4px 8px rgba(0,0,0,0.25)",
        shadow16Brand: "0 0 2px rgba(0,0,0,0.30), 0 8px 16px rgba(0,0,0,0.25)",
        shadow28Brand: "0 0 8px rgba(0,0,0,0.30), 0 14px 28px rgba(0,0,0,0.25)",
        shadow64Brand: "0 0 8px rgba(0,0,0,0.30), 0 32px 64px rgba(0,0,0,0.25)"
    };

    return theme;
};
