export interface AppThemeTokens {
    headerBackground: string;
    headerHover: string;
    headerPressed: string;
    headerSubtle: string;
    surfaceBase: string;
    surfaceRaised: string;
    surfaceSubtle: string;
    primaryBase: string;
    primaryHover: string;
    primaryPressed: string;
    primarySubtle: string;
    primarySubtleOn: string;
    primaryStrong: string;
    textDefault: string;
    textSecondary: string;
    textTertiary: string;
    textOnHeader: string;
    textOnPrimary: string;
    outlineSubtle: string;
    outlineBase: string;
    outlineHover: string;
    focusRing: string;
    disabledBackground: string;
    disabledForeground: string;
    disabledBorder: string;
    statusSuccessBackground: string;
    statusSuccessBorder: string;
    statusSuccessForeground: string;
    statusWarningBackground: string;
    statusWarningBorder: string;
    statusWarningForeground: string;
    statusErrorBackground: string;
    statusErrorBorder: string;
    statusErrorForeground: string;
    statusInfoBackground: string;
    statusInfoBorder: string;
    statusInfoForeground: string;
}

export const lightThemeTokens: AppThemeTokens = {
    headerBackground: "#1A4DBB",
    headerHover: "#183981",
    headerPressed: "#122C66",
    headerSubtle: "#DBEAFE",
    surfaceBase: "#F7F9FD",
    surfaceRaised: "#FFFFFF",
    surfaceSubtle: "#EEF3FF",
    primaryBase: "#1A4DBB",
    primaryHover: "#183981",
    primaryPressed: "#183981",
    primarySubtle: "#DBEAFE",
    primarySubtleOn: "#1E3A8A",
    primaryStrong: "#1E40AF",
    textDefault: "#182033",
    textSecondary: "#495775",
    textTertiary: "#687694",
    textOnHeader: "#F7F9FD",
    textOnPrimary: "#FFFFFF",
    outlineSubtle: "#D7E0F2",
    outlineBase: "#B8C7E6",
    outlineHover: "#7E97CC",
    focusRing: "#2563EB",
    disabledBackground: "#EEF1F7",
    disabledForeground: "#8B93A6",
    disabledBorder: "#D8DFEC",
    statusSuccessBackground: "#E7F6EE",
    statusSuccessBorder: "#8CC9A6",
    statusSuccessForeground: "#14532D",
    statusWarningBackground: "#FFF4DB",
    statusWarningBorder: "#E0A63A",
    statusWarningForeground: "#7A4B00",
    statusErrorBackground: "#FDECEC",
    statusErrorBorder: "#E37D7D",
    statusErrorForeground: "#8A1C1C",
    statusInfoBackground: "#E8F1FB",
    statusInfoBorder: "#7BA7D9",
    statusInfoForeground: "#1E4E8C"
};

export const darkThemeTokens: AppThemeTokens = {
    headerBackground: "#1C3766",
    headerHover: "#6F90D8",
    headerPressed: "#5A7FCF",
    headerSubtle: "#1E3A8A",
    surfaceBase: "#0F172D",
    surfaceRaised: "#172346",
    surfaceSubtle: "#13203C",
    primaryBase: "#86A4E5",
    primaryHover: "#A0B8ED",
    primaryPressed: "#6F90D8",
    primarySubtle: "#1A4DBB",
    primarySubtleOn: "#DBEAFE",
    primaryStrong: "#2563EB",
    textDefault: "#F4F7FF",
    textSecondary: "#D4DDF4",
    textTertiary: "#AAB8D9",
    textOnHeader: "#F4F7FF",
    textOnPrimary: "#F4F7FF",
    outlineSubtle: "#29385C",
    outlineBase: "#3D5287",
    outlineHover: "#6784CC",
    focusRing: "#86A4E5",
    disabledBackground: "#18213A",
    disabledForeground: "#7482A6",
    disabledBorder: "#2A3860",
    statusSuccessBackground: "#16382B",
    statusSuccessBorder: "#4D8F69",
    statusSuccessForeground: "#BEE7CC",
    statusWarningBackground: "#3A2C12",
    statusWarningBorder: "#B98A2F",
    statusWarningForeground: "#F4D58D",
    statusErrorBackground: "#3B1E22",
    statusErrorBorder: "#B86A74",
    statusErrorForeground: "#F2C0C7",
    statusInfoBackground: "#182D42",
    statusInfoBorder: "#5D88B8",
    statusInfoForeground: "#BDD8F5"
};
