export interface AppThemeTokens {
    headerBackground: string;
    headerHover: string;
    headerSubtle: string;
    surfaceBase: string;
    surfaceRaised: string;
    surfaceSubtle: string;
    primaryBase: string;
    primaryHover: string;
    primaryPressed: string;
    primarySubtle: string;
    primaryStrong: string;
    primaryOn: string;
    textPrimary: string;
    textSecondary: string;
    textTertiary: string;
    textOnHeader: string;
    textOnPrimary: string;
    outlineSubtle: string;
    outlineBase: string;
    outlineStrong: string;
    focusRing: string;
    statusSuccessBackground: string;
    statusSuccessBorder: string;
    statusSuccessForeground: string;
    statusWarningBackground: string;
    statusWarningBorder: string;
    statusWarningForeground: string;
    statusErrorBackground: string;
    statusErrorBorder: string;
    statusErrorForeground: string;
    statusInfoBackground: string;
    statusInfoBorder: string;
    statusInfoForeground: string;
}

export const lightThemeTokens: AppThemeTokens = {
    headerBackground: "#395B52",
    headerHover: "#46695F",
    headerSubtle: "#E3ECE9",
    surfaceBase: "#F7FAF8",
    surfaceRaised: "#FFFFFF",
    surfaceSubtle: "#E6EFED",
    primaryBase: "#94B9AF",
    primaryHover: "#7EA79C",
    primaryPressed: "#688F85",
    primarySubtle: "#E3EFEB",
    primaryStrong: "#5F8F82",
    primaryOn: "#001412",
    textPrimary: "#191C1B",
    textSecondary: "#5C6664",
    textTertiary: "#7B8582",
    textOnHeader: "#F7FAF8",
    textOnPrimary: "#001412",
    outlineSubtle: "#D7E2DE",
    outlineBase: "#BEC9C6",
    outlineStrong: "#97A7A2",
    focusRing: "#5F8F82",
    statusSuccessBackground: "#E7F6EE",
    statusSuccessBorder: "#8CC9A6",
    statusSuccessForeground: "#14532D",
    statusWarningBackground: "#FFF4DB",
    statusWarningBorder: "#E0A63A",
    statusWarningForeground: "#7A4B00",
    statusErrorBackground: "#FDECEC",
    statusErrorBorder: "#E37D7D",
    statusErrorForeground: "#8A1C1C",
    statusInfoBackground: "#E8F1FB",
    statusInfoBorder: "#7BA7D9",
    statusInfoForeground: "#1E4E8C"
};

export const darkThemeTokens: AppThemeTokens = {
    headerBackground: "#567E74",
    headerHover: "#6A9589",
    headerSubtle: "#29453E",
    surfaceBase: "#102824",
    surfaceRaised: "#193A34",
    surfaceSubtle: "#14312C",
    primaryBase: "#94B9AF",
    primaryHover: "#A7C8BF",
    primaryPressed: "#7EA79C",
    primarySubtle: "#21423A",
    primaryStrong: "#5F8F82",
    primaryOn: "#001412",
    textPrimary: "#F3F7F5",
    textSecondary: "#C2D1CC",
    textTertiary: "#93A7A0",
    textOnHeader: "#081512",
    textOnPrimary: "#001412",
    outlineSubtle: "#2C4A43",
    outlineBase: "#3F6259",
    outlineStrong: "#5A8479",
    focusRing: "#94B9AF",
    statusSuccessBackground: "#16382B",
    statusSuccessBorder: "#4D8F69",
    statusSuccessForeground: "#BEE7CC",
    statusWarningBackground: "#3A2C12",
    statusWarningBorder: "#B98A2F",
    statusWarningForeground: "#F4D58D",
    statusErrorBackground: "#3B1E22",
    statusErrorBorder: "#B86A74",
    statusErrorForeground: "#F2C0C7",
    statusInfoBackground: "#182D42",
    statusInfoBorder: "#5D88B8",
    statusInfoForeground: "#BDD8F5"
};
