export interface AppThemeTokens {
    headerBackground: string;
    headerHover: string;
    headerPressed: string;
    surfaceBase: string;
    surfaceRaised: string;
    surfaceSubtle: string;
    primaryBase: string;
    primaryHover: string;
    primaryPressed: string;
    primarySubtle: string;
    primarySubtleOn: string;
    primaryStrong: string;
    textDefault: string;
    textSecondary: string;
    textTertiary: string;
    textOnHeader: string;
    textOnPrimary: string;
    outlineSubtle: string;
    outlineBase: string;
    outlineHover: string;
    focusRing: string;
    disabledBackground: string;
    disabledForeground: string;
    disabledBorder: string;
    statusSuccessBackground: string;
    statusSuccessBorder: string;
    statusSuccessForeground: string;
    statusWarningBackground: string;
    statusWarningBorder: string;
    statusWarningForeground: string;
    statusErrorBackground: string;
    statusErrorBorder: string;
    statusErrorForeground: string;
    statusInfoBackground: string;
    statusInfoBorder: string;
    statusInfoForeground: string;
}

export const lightThemeTokens: AppThemeTokens = {
    headerBackground: "#2563eb",
    headerHover: "#1d4ed8",
    headerPressed: "#1e40af",
    surfaceBase: "#f8fafc",
    surfaceRaised: "#f1f5f9",
    surfaceSubtle: "#FFFFFF",
    primaryBase: "#2563eb",
    primaryHover: "#1d4ed8",
    primaryPressed: "#1e40af",
    primarySubtle: "#DBEAFE",
    primarySubtleOn: "#1E3A8A",
    primaryStrong: "#1A4DBB",
    textDefault: "#1E293B",
    textSecondary: "#334155",
    textTertiary: "#526077",
    textOnHeader: "#FFFFFF",
    textOnPrimary: "#FFFFFF",
    outlineSubtle: "#D7E0F2",
    outlineBase: "#B8C7E6",
    outlineHover: "#7E97CC",
    focusRing: "#2563EB",
    disabledBackground: "#EEF1F7",
    disabledForeground: "#8B93A6",
    disabledBorder: "#D8DFEC",
    statusSuccessBackground: "#E7F6EE",
    statusSuccessBorder: "#8CC9A6",
    statusSuccessForeground: "#14532D",
    statusWarningBackground: "#FFF4DB",
    statusWarningBorder: "#E0A63A",
    statusWarningForeground: "#744904",
    statusErrorBackground: "#FDECEC",
    statusErrorBorder: "#E37D7D",
    statusErrorForeground: "#8A1C1C",
    statusInfoBackground: "#E8F1FB",
    statusInfoBorder: "#7BA7D9",
    statusInfoForeground: "#1E4E8C"
};

export const darkThemeTokens: AppThemeTokens = {
    headerBackground: "#2563eb",
    headerHover: "#1d4ed8",
    headerPressed: "#1e40af",
    surfaceBase: "#0F172D",
    surfaceRaised: "#020617",
    surfaceSubtle: "#13203C",
    primaryBase: "#86A4E5",
    primaryHover: "#A0B8ED",
    primaryPressed: "#6F90D8",
    primarySubtle: "#1A4DBB",
    primarySubtleOn: "#DBEAFE",
    primaryStrong: "#2563EB",
    textDefault: "#F1F5F9",
    textSecondary: "#94A3B8",
    textTertiary: "#64748B",
    textOnHeader: "#FFFFFF",
    textOnPrimary: "#080E1E",
    outlineSubtle: "#1E293B",
    outlineBase: "#334155",
    outlineHover: "#475569",
    focusRing: "#86A4E5",
    disabledBackground: "#1E293B",
    disabledForeground: "#475569",
    disabledBorder: "#1E293B",
    statusSuccessBackground: "#16382B",
    statusSuccessBorder: "#4D8F69",
    statusSuccessForeground: "#BEE7CC",
    statusWarningBackground: "#3A2C12",
    statusWarningBorder: "#B98A2F",
    statusWarningForeground: "#F4D58D",
    statusErrorBackground: "#3B1E22",
    statusErrorBorder: "#B86A74",
    statusErrorForeground: "#F2C0C7",
    statusInfoBackground: "#182D42",
    statusInfoBorder: "#5D88B8",
    statusInfoForeground: "#BDD8F5"
};
