permissions:
  contents: read
name: Frontend build test

on: [push, workflow_dispatch]

jobs:
  test_frontend:
    name: Test Frontend on ${{ matrix.os }} Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04"]
        node_version: ["20"]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install dependencies
        run: |
          cd ./mucgpt-frontend
          npm install
      - name: Build frontend
        run: |
          cd ./mucgpt-frontend
          npm run build
