name: Build and Push Images

on:
  push:
    branches: [ main ]
    paths:
      - 'mucgpt-frontend/**'
      - 'mucgpt-assistant-service/**'
      - 'mucgpt-core-service/**'
      - '.github/workflows/build-and-push-images.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'mucgpt-frontend/**'
      - 'mucgpt-assistant-service/**'
      - 'mucgpt-core-service/**'
      - '.github/workflows/build-and-push-images.yml'
  # workflow_dispatch works on all branches by default
  workflow_dispatch:
    inputs:
      build-frontend:
        description: 'Build and push frontend image'
        required: true
        default: 'true'
        type: boolean
      build-assistant:
        description: 'Build and push assistant service image'
        required: true
        default: 'true'
        type: boolean
      build-core:
        description: 'Build and push core service image'
        required: true
        default: 'true'
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  determine-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      assistant: ${{ steps.filter.outputs.assistant }}
      core: ${{ steps.filter.outputs.core }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if workflow dispatch with parameters
        id: workflow-dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "frontend=${{ github.event.inputs.build-frontend == 'true' }}" >> $GITHUB_OUTPUT
          echo "assistant=${{ github.event.inputs.build-assistant == 'true' }}" >> $GITHUB_OUTPUT
          echo "core=${{ github.event.inputs.build-core == 'true' }}" >> $GITHUB_OUTPUT

      - name: Check for changes
        if: github.event_name != 'workflow_dispatch'
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'mucgpt-frontend/**'
            assistant:
              - 'mucgpt-assistant-service/**'
            core:
              - 'mucgpt-core-service/**'

      - name: Set final outputs
        id: set-outputs
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "frontend=${{ steps.workflow-dispatch.outputs.frontend }}" >> $GITHUB_OUTPUT
            echo "assistant=${{ steps.workflow-dispatch.outputs.assistant }}" >> $GITHUB_OUTPUT
            echo "core=${{ steps.workflow-dispatch.outputs.core }}" >> $GITHUB_OUTPUT
          else
            echo "frontend=${{ steps.filter.outputs.frontend }}" >> $GITHUB_OUTPUT
            echo "assistant=${{ steps.filter.outputs.assistant }}" >> $GITHUB_OUTPUT
            echo "core=${{ steps.filter.outputs.core }}" >> $GITHUB_OUTPUT
          fi

  build-frontend:
    needs: determine-changes
    if: needs.determine-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push Frontend image
        uses: it-at-m/lhm_actions/action-templates/actions/action-build-image@v1.0.20
        with:
          registry: "ghcr.io"
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          image-tags: |
            type=raw,value=latest
            type=sha,format=short
            type=ref,event=branch
            type=ref,event=tag
          image-labels: |
            org.opencontainers.image.description=MUCGPT Frontend - See ${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          path: ./mucgpt-frontend
          image-name: ${{ github.repository_owner }}/mucgpt/frontend

  build-assistant:
    needs: determine-changes
    if: needs.determine-changes.outputs.assistant == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push Assistant Service image
        uses: it-at-m/lhm_actions/action-templates/actions/action-build-image@v1.0.20
        with:
          registry: "ghcr.io"
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          image-tags: |
            type=raw,value=latest
            type=sha,format=short
            type=ref,event=branch
            type=ref,event=tag
          image-labels: |
            org.opencontainers.image.description=MUCGPT Assistant Service - See ${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          path: ./mucgpt-assistant-service
          image-name: ${{ github.repository_owner }}/mucgpt/assistant-service

  build-core:
    needs: determine-changes
    if: needs.determine-changes.outputs.core == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push Core Service image
        uses: it-at-m/lhm_actions/action-templates/actions/action-build-image@v1.0.20
        with:
          registry: "ghcr.io"
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          image-tags: |
            type=raw,value=latest
            type=sha,format=short
            type=ref,event=branch
            type=ref,event=tag
          image-labels: |
            org.opencontainers.image.description=MUCGPT Core Service - See ${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          path: ./mucgpt-core-service
          image-name: ${{ github.repository_owner }}/mucgpt/core-service
