name: Python check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_package:
    name: Test ${{ matrix.os }} Python ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04"]
        python_version: ["3.12"]
    steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        - name: Install the latest version of uv
          uses: astral-sh/setup-uv@caf0cab7a618c569241d31dcd442f54681755d39 # v3.2.4
          with:
            version: "latest"
            architecture: x64
        - name: Setup node
          uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
          with:
            node-version: 20
        - name: Build frontend
          run: |
            cd ./app/frontend
            npm install
            npm run buildlocal
        - name: Install dependencies
          run: |
            uv sync --all-extras
        - name: Lint with ruff
          run: uv run ruff check .
        - name: Run Python tests
          run: uv run pytest
