name: build
on:
  pull_request:
jobs:
  build:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy Security check on Repository
        uses: it-at-m/lhm_actions/action-templates/actions/action-trivy@acb09213786b76dd7aa52ec1d901390d28c60eb0 # v1.0.29
