name: build
on:
  pull_request:
permissions:
  contents: read
jobs:
  build:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy Security check on Repository
        uses: it-at-m/lhm_actions/action-templates/actions/action-trivy@7cb754b2056cebda6c36db344434f85be398c493 # v1.0.25
