name: build
on:
  pull_request:
jobs:
  build:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy Security check on Repository
        uses: it-at-m/lhm_actions/action-templates/actions/action-trivy@b088b94cad35e50b197104c9e2ac8fb25a7116b3 # v1.0.33
